In [93]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [94]:
df = pd.read_csv('../data/movies_ratings.csv')

In [95]:
X = df.values

In [96]:
r = cosine_similarity(X)

In [97]:
r.shape

(671, 671)

In [105]:
np.dot(X, X.T).shape

(671, 671)

In [60]:
X.shape

(671, 2794)

In [68]:
t.shape

(671, 671)

In [102]:
l2 = lambda X: np.sqrt(np.sum(X ** 2, axis=1))

In [103]:
X_l2 = l2(X)

In [104]:
X_l2.shape

(671,)

In [106]:
r = (X @ X.T) / (X_l2.T * X_l2)

In [107]:
r.shape

(671, 671)

In [108]:
r

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.27392739, ..., 0.09411765, 0.29044118,
        0.11082138],
       [0.        , 0.10835509, 1.        , ..., 0.14705882, 0.24632353,
        0.13168188],
       ...,
       [0.        , 0.02088773, 0.08250825, ..., 1.        , 0.        ,
        0.05867014],
       [0.        , 0.10313316, 0.22112211, ..., 0.        , 1.        ,
        0.12125163],
       [0.        , 0.11096606, 0.33333333, ..., 0.26470588, 0.34191176,
        1.        ]])

In [92]:
r

array([[5.62031215e-05, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.30459367e-03, 1.41359366e-04, ...,
        2.72499983e-05, 1.34546867e-04, 1.44765616e-04],
       [0.00000000e+00, 1.41359366e-04, 5.16046843e-04, ...,
        4.25781223e-05, 1.14109368e-04, 1.72015614e-04],
       ...,
       [0.00000000e+00, 2.72499983e-05, 4.25781223e-05, ...,
        2.89531232e-04, 0.00000000e+00, 7.66406202e-05],
       [0.00000000e+00, 1.34546867e-04, 1.14109368e-04, ...,
        0.00000000e+00, 4.63249971e-04, 1.58390615e-04],
       [0.00000000e+00, 1.44765616e-04, 1.72015614e-04, ...,
        7.66406202e-05, 1.58390615e-04, 1.30629679e-03]])

In [75]:
X_l2.T.shape

(1, 671)

In [78]:
t = X_l2.T @ X_l2

In [79]:
t.shape

(1, 1)

In [83]:
t[0][0]

587156.0

In [109]:
m = X.mean(axis=1)

In [112]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
def pearsonr(X):
    m = X.shape[1]
    res = np.eye(m)
    mean_ = X.mean(axis=1)
    for i in range(m - 1):
        for j in range(i + 1, m):
            t_i = (X[:, i] - mean_)
            t_j = (X[:, j] - mean_)
            denominator = np.sum(t_i ** 2) * np.sum(t_j ** 2)
            res[i, j] = np.sum(t_i * t_j) / denominator
            res[j, i] = res[i, j]

    return res

In [116]:
pearsonr(X)

array([[ 1.00000000e+00,  3.18066199e-02,  2.35962989e-02, ...,
        -1.13615025e-03,  1.34143517e-02,  1.28003652e-02],
       [ 3.18066199e-02,  1.00000000e+00,  2.43319701e-02, ...,
        -1.19988946e-03,  3.52373633e-02,  3.46299890e-02],
       [ 2.35962989e-02,  2.43319701e-02,  1.00000000e+00, ...,
        -1.06781417e-03,  1.02061357e-02,  9.62439941e-03],
       ...,
       [-1.13615025e-03, -1.19988946e-03, -1.06781417e-03, ...,
         1.00000000e+00, -7.23022967e-04, -1.13548282e-03],
       [ 1.34143517e-02,  3.52373633e-02,  1.02061357e-02, ...,
        -7.23022967e-04,  1.00000000e+00,  1.46336162e-02],
       [ 1.28003652e-02,  3.46299890e-02,  9.62439941e-03, ...,
        -1.13548282e-03,  1.46336162e-02,  1.00000000e+00]])